version: "3"
services:
  app:
    image: node:lts
    build: ./server
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: "sh -c 'cd /app && npm install && npm run dev'"
    volumes:
      - ./server:/app

  postgres:
    image: postgres:latest
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

  front:
    build: ./front
    depends_on:
      - app
    environment:
      NODE_ENV: development
      NODE_OPTIONS: --openssl-legacy-provider
      PORT: 8000
    ports:
      - "8000:8000"
    command: >
      bash -c " npm install --save axios vue-axios && npm run serve"
    volumes:
      - ./front:/app
      - /app/node_modules
